active_directory:
  ad_domain_controller:
    default: ''
    client: true
  ad_domain_controller_port:
    default: '389'
    client: true
  ad_base_dn:
    default: ''
    client: true
  ad_bind_dn:
    default: ''
    client: true
  ad_bind_pass:
    default: ''
    client: true
  ad_login_attribute:
    default: 'sAMAccountName'
    client: true
